language: python

env:
 - wagtail_version=2.7.1  # LTS
 - wagtail_version=2.8

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

#matrix:
#  exclude:
#  - python: "3.7"
#    env: wagtail_version=1.11.8
#  - python: "3.8"
#    env: wagtail_version=1.11.8
#  - python: "2.7"
#    env: wagtail_version=3.0.2
#  - python: "3.5"
#    env: wagtail_version=3.0.2
#  - python: "pypy"
#    env: wagtail_version=3.0.2

install:
 - pip install -q wagtail==$wagtail_version tablib[xls,xlsx]

script:
 - python runtests.py
